id: P006814
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1016956
  title: དྲང་ངེས་རྣམ་འབྱེད་ཀྱི་བཀའ་འགྲེལ་རབ་ཏུ་གསལ་བར་བྱེད་པའི་སྒྲོན་མེ
  author: ''
  volumes:
    40789c3c6aca43b5ad90b869cfca35bd:
      image_group_id: I01JW182
      title: ''
      volume_number: 1
      total_pages: 216
      base_file: v001.txt
