id: P006814
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 12:24:28.874393
source_metadata:
  id: bdr:W00EGS1016956
  title: དྲང་ངེས་རྣམ་འབྱེད་ཀྱི་བཀའ་འགྲེལ་རབ་ཏུ་གསལ་བར་བྱེད་པའི་སྒྲོན་མེ
  author: ''
  volumes:
    40789c3c6aca43b5ad90b869cfca35bd:
      image_group_id: I01JW182
      title: ''
      volume_number: 1
      total_pages: 216
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
