id: I76FE175F
legacy_id: P006814
ocr_import_info:
  bdrc_scan_id: W00EGS1016956
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T07:49:18'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T10:51:59.118163+00:00'
last_modified: 2022-08-29 18:52:22.097078
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00EGS1016956
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW00EGS1016956
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དྲང་ངེས་རྣམ་འབྱེད་ཀྱི་བཀའ་འགྲེལ་རབ་ཏུ་གསལ་བར་བྱེད་པའི་སྒྲོན་མེ།
  author: ཏཱ་ལའི་བླ་མ ༠༢་དགེ་འདུན་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.6212808914065071
  ocr_word_median_confidence_index: 0.6700000166893005
quality: null
bases:
  I01JW182:
    source_metadata:
      id: http://purl.bdrc.io/resource/I01JW182
      total_pages: 216
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I01JW182.txt
    statistics:
      ocr_word_median_confidence_index: 0.6700000166893005
      ocr_word_mean_confidence_index: 0.6212808914065071
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
